### ISSUE TITLE
Expansion for CamelCase elements

### ISSUE THREAD

**Issue by i5ar** [FallenMax/mithril-emmet#1]
Hi,
I'd like to use this extension with [React Hyperscript](https://github.com/mlmorg/react-hyperscript) or eventually with [Dojo](https://dojo.io/tutorials/003_creating_widgets/#7)

For this to work the quotes should not be applied if the element is CamelCase.
For instance `AppWrapper>Helmet` should expand:

    h(AppWrapper, 
      h(Helmet)
    )

and not:

    h('AppWrapper', 
      h('Helmet')
    )

Anyway, groups (e.g. `one>(two>three)+four`) seem to have some strange behavior. Are they supported?
Thank you!

**Comment by FallenMax** [comment]
@i5ar Good suggestion! Will look into this and make a patch asap.

**Comment by FallenMax** [comment]
@i5ar feature added on 0.7.0
relevant commit: 08547ffb4b4a7496605e333c19f43f06dfd4e8c5
