### ISSUE TITLE
Auto Suggestion not working

### ISSUE THREAD

**Issue by ariam2023** [FallenMax/mithril-emmet#11]
Type: <b>Performance Issue</b>

The Emmet extension is not working for me suddenly stopped functioning properly as intended, I have no idea how it started.  I kept uninstalling and installing it back, even tried an old version but I see no difference.

Extension version: 0.7.7
VS Code version: Code 1.93.1 (38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40, 2024-09-11T17:20:05.685Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by ariam2023** [comment]
![image](https://github.com/user-attachments/assets/0974d0c3-f012-4a10-bf4d-4a425dd00408)

**Comment by ariam2023** [comment]
Thank you in advance!!!

**Comment by ariam2023** [comment]
Thanks

**Comment by FallenMax** [comment]
Hi @ariam2023 , Mithril Emmet is not quite related to the functionality your screenshot shows here:

https://github.com/FallenMax/mithril-emmet#:~:text=is%20a%20built%2Din%20feature%20of%20VS%20Code
