### ISSUE TITLE
Icon (greater-than sign)

### ISSUE THREAD

**Issue by i5ar** [FallenMax/mithril-emmet#2]
Last night I designed a very simple [icon](https://gist.github.com/i5ar/38e575037a6dfce89578dbb7b2f51760) for this extension so I can easily spot it in the extensions pane.
Feel free to take it if you like it.
Feel also free to change color, shape and whatnot.

**Comment by FallenMax** [comment]
@i5ar  Thanks for your work and reminder! This little extension do need an icon. 
To make it less indistinguishable and (more or less) convey its purpose, I spent 2 hours and made one (by grabbing Emmet's icon and hacking a little). I'm completely noob at design and hope it's not too awful.
Please upgrade extension and take a look. Any improvement and suggestion is welcomed!

**Comment by i5ar** [comment]
@FallenMax That's great!
