### ISSUE TITLE
Add support Twig by default without any conf

### ISSUE THREAD

**Issue by alexandre-leng** [FallenMax/mithril-emmet#6]
Issue Type: <b>Feature Request</b>

Hi

i think it can be great for beginners and student to add twig to emmet extension default without any conf .

Emmet team say i need to report this feature request here

Have a niced day 
Alexander

Extension version: 0.7.6
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042

**Comment by FallenMax** [comment]
Sorry but it doesn't has anything to do with this extension, this extension is used to create `hyperscript` from emmet abbreviation:

emmet:
```
div>h1+h2
```

generated hyperscript:

```
<div><h1></h1><h2></h2></div>
```
